import os
import sys
import rtconfig

from rtconfig import RTT_ROOT

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
from building import *

TARGET = 'rtthread.' + rtconfig.TARGET_EXT

DefaultEnvironment(tools=[])
env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CFLAGS = rtconfig.CFLAGS,
    CXX = rtconfig.CXX, CXXFLAGS = rtconfig.CXXFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)
env.AppendUnique(LIBS=['m'])
env['ASCOM'] = env['ASPPCOM']

Export('RTT_ROOT')
Export('rtconfig')

env.AppendUnique(CPPPATH=[
    os.path.join(os.getcwd(), 'compat_include'),
    os.path.join(RTT_ROOT, 'libcpu', 'aarch64', 'common', 'include'),
    os.path.join(RTT_ROOT, 'components'),
    os.path.join(RTT_ROOT, 'components', 'drivers', 'include'),
    os.path.join(RTT_ROOT, 'components', 'drivers', 'ofw'),
    os.path.join(RTT_ROOT, 'components', 'drivers', 'ofw', 'libfdt'),
    os.path.join(RTT_ROOT, 'components', 'net', 'lwip', 'lwip-2.0.3', 'src', 'include'),
    os.path.join(RTT_ROOT, 'components', 'net', 'lwip', 'lwip-2.0.3', 'src', 'include', 'ipv4'),
    os.path.join(RTT_ROOT, 'components', 'net', 'lwip', 'lwip-2.0.3', 'src', 'include', 'ipv6'),
    os.path.join(RTT_ROOT, 'components', 'net', 'lwip', 'port'),
    os.path.join(RTT_ROOT, 'components', 'net', 'netdev', 'include'),
    os.path.join(RTT_ROOT, 'components', 'utilities', 'libadt', 'avl'),
    os.path.join(RTT_ROOT, 'components', 'utilities', 'libadt', 'bitmap'),
    os.path.join(RTT_ROOT, 'components', 'utilities', 'libadt', 'hashmap'),
    os.path.join(RTT_ROOT, 'components', 'utilities', 'libadt', 'ref'),
])

# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT, has_libcpu = False)
objs += env.Object(os.path.join('compat_include', 'string_ext.c'))
objs += env.Object(os.path.join('compat_include', 'time_compat.c'))
objs += env.Object(os.path.join('compat_include', 'newlib_stubs.c'))

# make a building
DoBuilding(TARGET, objs)
